const inputFields = [
  {
    id: "Tittle",
    label: "Tittle",
    type: "text",
    placeholder: "Movie Name",
    validation: { required: "Field is required" },
  },
  {
    id: "ReleaseDate",
    label: "ReleaseDate",
    type: "date",
    validation: { required: "Field is required" },
  },
  {
    id: "Duration",
    label: "Duration",
    type: "text",
    placeholder: "hh.mm.ss",
    validation: { required: "Field is required" },
  },
  {
    id: "Genre",
    label: "Genre",
    type: "text",
    placeholder: "Drama,Horror,Fantasy...ect",
    validation: { required: "Field is required" },
  },
  {
    id: "PlotSummary",
    label: "PlotSummary",
    type: "text",
    placeholder: "Plot Storie",
    validation: { required: "Field is required" },
  },
  {
    id: "Discription",
    label: "Discription",
    type: "text",
    placeholder: "discription about movie",
    validation: { required: "Field is required" },
  },
  {
    id: "Language",
    label: "Language",
    type: "text",
    placeholder: "MovieLanguage",
    validation: { required: "Field is required" },
  },
  {
    id: "CountryofOrigin",
    label: "CountryofOrigin",
    type: "text",
    placeholder: "USA,IN,US...",
    validation: { required: "Field is required" },
  },
  {
    id: "NativeLanguage",
    label: "NativeLanguage",
    type: "text",
    placeholder: "English,Hindi,Tamil...",
    validation: { required: "Field is required" },
  },
  {
    id: "StreamingPlatforms",
    label: "StreamingPlatforms",
    type: "text",
    placeholder: "AmazonPrime,HotStar,Netflix...",
    validation: { required: "Field is required" },
  },
  {
    id: "Director",
    label: "Director",
    type: "text",
    placeholder: "movie director",
    validation: { required: "Field is required" },
  },
  {
    id: "MoviePosters",
    label: "MoviePosters",
    type: "text",
    placeholder: "Image url link",
    validation: { required: "Field is required" },
  },
];

export default inputFields;
